### PR TITLE
Enhancements

### LINKED ISSUE #1: Failure when mounted volume is a file
It fails when a volume is mounted to a file. Maybe those bindings should be ignored ?

### PR DESCRIPTION
**Pull request by Toilal**
These are mainly logs enhancements to diagnose possible issues, and it fixes #1 by ignoring file binding volumes.

### CODE REVIEW

**Comment by Toilal** [comment]
Sadly, I won't use this project and enable a file polling mode on the container dev server. For some reason (unrelated to this project), inotify works weel a few times after container start, but later it just doesn't work.

**Comment by merofeev** [comment]
@Toilal thanks for doing this! I will test your PR a little bit this evening and then merge it.

Considering your second issue. Are you sure this is not related to docker-windows-volume-watcher? Does your container and/or host delete files in mounted directory (I believe there is some issue with file deletion, that might break everything).

Anyway, thanks for your contribution!

**Comment by Toilal** [comment]
Yes, I'm sure it's not related to this project because i've done some tests while NOT running it :

If I change files using sed from within the container (using docker exec), changes are detected 2 or 3 times, and then it doesn't detect changes anymore.

**Review by merofeev — APPROVED** [review]
Fixes #1 for me as well.

**Pull request merged**
